### ISSUE TITLE
Vaccination data issue

### ISSUE THREAD

**Issue by sjbeckett** [appliedbinf/c19rdata#2]
Hi, @ar0ch and @freyja-bt.
The output of this operation produces entries with a date of NA (for some counties) at the tail of those counties entries https://github.com/appliedbinf/c19rdata/blob/0e906706504f3c836d00b7250aa7cd045e8751d7/R/makeDailyMaps.R#L65

e.g. looking at Los Angeles county
`tail(vacc_data_fill[which(vacc_data_fill$county=="6037"),])`

```
# A tibble: 6 x 5
  date       county cnt_fully_vacc last_date  is_last
  <date>      <dbl>          <dbl> <date>     <lgl>  
1 2021-12-12   6037       6752641. 2021-12-07 FALSE  
2 2021-12-13   6037       6766574. 2021-12-07 FALSE  
3 2021-12-14   6037       6780506. 2021-12-07 FALSE  
4 2021-12-15   6037       6794438  2021-12-15 FALSE  
5 2021-12-16   6037      12463202. 2021-12-15 FALSE  
6 NA           6037      18131967  2021-12-15 FALSE

```
This causes downstream issues for those counties in which an NA date is recorded.

Suggest adding something to the effect of 
`vacc_data = vacc_data[-which(is.na(vacc_data$date)),]`
at L93

which instead produces:
`tail(vacc_data_fill[which(vacc_data_fill$county=="6037"),])`
```
# A tibble: 6 x 5
  date       county cnt_fully_vacc last_date  is_last
  <date>      <dbl>          <dbl> <date>     <lgl>  
1 2021-12-11   6037       6738709  2021-12-07 FALSE  
2 2021-12-12   6037       6752641. 2021-12-07 FALSE  
3 2021-12-13   6037       6766574. 2021-12-07 FALSE  
4 2021-12-14   6037       6780506. 2021-12-07 FALSE  
5 2021-12-15   6037       6794438  2021-12-15 FALSE  
6 2021-12-16   6037       6794438  2021-12-15 TRUE
```

**Comment by freyja-bt** [comment]
I recommend making the change at line 65, changing `vacc_data <- vacc_data %>%...` to either `vacc_data = vacc_data[-which(is.na(vacc_data$DATE)),]%>%...` or `vacc_data %>% tidyr::drop_na(DATE) %>%...`.
The error is caused by an issue in the Bansal data where weeks 1-3 of 2021 are missing the dates. When the data is sorted the NAs are put chronologically last.

**Comment by sjbeckett** [comment]
Just a quick note that immunity is currently listed as NA for all counties, suggesting another issue at hand.

**Comment by freyja-bt** [comment]
> Just a quick note that immunity is currently listed as NA for all counties, suggesting another issue at hand.
As referenced [on the Bansal Lab page](https://github.com/bansallab/vaccinetracking/tree/main/vacc_data#updates), 

> Data will not be updated for the last two weeks of 2021. Data will be updated next in January 2022 and will include data updates for the last two weeks of 2021

Two options I can think of: (1) interpolate data out to `past_date` in L95-104 or (2) filter the data at L143 by `dplyr::if_else(past_date %in% vacc_data_fill$date, past_date, ex_dates[2])`, so if `past_date` isn't an option, it will default back to the the last available date in the dataset.

**Comment by sjbeckett** [comment]
That explains a lot! I think we were using option (2) in the initial test server (that @freyja-bt deployed) with an extra line in the hover text to note the difference in update timing between datasets (when one exists). It looks like we have some of the infrastructure already built in to use this approach here too. Unless there are other reasons that mean we can't?

**Comment by freyja-bt** [comment]
It wasn't exactly the same bc it only filled the data to the last Bansal date, not the current date, but I can make it do that!

This is more similar to (1) but with "fill" instead of "interpolate," which is what I should have suggested. Assuming the code still exists in the current app build (I haven't checked) that will be straightforward and integrate well.

**Comment by sjbeckett** [comment]
I might be wrong, but I think that is what `vacc_data_fill` is attempting to calculate! Sounds good!

**Comment by freyja-bt** [comment]
Correct. Changing `ex_dates[2]` to `max(<its current value>, past_date)` will solve the issue.
